### ISSUE TITLE
Multiple load paths in .load()

### ISSUE THREAD

**Issue by jongyonkim** [databricks/spark-avro#100]
It looks like support for multiple load paths via .load() is not consistent with that of spark-csv.

For example, this works in spark-csv:
val df = sqlContext.read.format("com.databricks.spark.csv").load("/path/data1.csv,/path/data2.csv")

When I try this in spark-avro:
val df = sqlContext.read.format("com.databricks.spark.avro").load("/path/data1.avro,/path/data2.avro")

It fails with the following message:
"java.io.FileNotFoundException: The path (/path/data1.avro,/path/data2.avro) is invalid."

1) Will the next version of spark-avro have that support (separate paths by a comma)?
2) How about changing the argument of .load() from a string to a list of paths (iterable)?

**Comment by koertkuipers** [comment]
spark-avro is based on HadoopFsRelationProvider which used to support comma separated paths like that but in spark 1.5 this stopped working (because people wanted support for paths with commas in it).

since spark-csv will probably also move to HadoopFsRelationProvider i expect this to also break in spark-csv at some point.

spark 1.6 will support varargs, so you can do:
sqlContext.read.format("com.databricks.spark.avro"").load("/path/data1.csv", "/path/data2.csv")

**Comment by wsurles** [comment]
Is there a workaround for 1.5?

**Comment by kurtharriger** [comment]
Is there a workaround for spark 1.5?

**Comment by kurtharriger** [comment]
DataFrame has a unionAll.  So to answer my own question, here is what I did to workaround the issue for now: 
```
val dfs =  input.split(",") map sqlContext.read.format(inputFormat).load
dfs.tail.foldLeft(dfs.head) { (df1, df2) => df1.unionAll(df2) }
```

**Comment by saravansekar** [comment]
The format to ready with sqlContext.read.format("com.databricks.spark.avro"").load("/path/", "/path/")  is not supported by the load function. will it be made sync with spark csv?

**Comment by joelpfaff** [comment]
On my side, I managed to get this working by generating a single string with all files to load:
fileList being the list of files to load
hadoop_root_path being the root directory
```
val load_str = hadoop_root_path + 
          fileList.map(file => file.substring(hadoop_root_path.length)).mkString("{", ",", "}")
```
This generates a string like this one:
/path/to/files/2013/01-{01/qwe123,01/asd123,01/zxc321,02/ert435,02/fgh987,03/vbn764}
That can be passed directly to sqlContext.read.format("com.databricks.spark.avro").load

This allowed us to not use a unionAll, because for a large number of files, unionAll was generating a very complex execution plan (and failed with a StackOverflow on the JVM with thousands of files).

**Comment by JoshRosen** [comment]
I think that this issue is now resolved:

1. The argument for avoiding Union is no longer necessary since the Spark 2.0 compatible versions of this library no longer use Union.
2. Newer versions support the varargs variant of `load()` via the Data sources API.
