### ISSUE TITLE
What About Initial ETL?

### ISSUE THREAD

**Issue by eljefe6a** [databricks/spark-avro#125]
The library excels at dealing reading in existing Avro and saving out DataFrames as Avro. It doesn't ease the burden of doing the initial ETL and saving to Avro.

[Here](https://github.com/eljefe6a/nfldata/blob/master/spark/src/main/java/solution/PlayByPlay.java#L81) is an example of what I'm talking about. I've read in the raw data and ETL'd it to Avro, the `Weather` object in this case. In order to make it a DataFrame and save it, I have to [manually convert](https://github.com/eljefe6a/nfldata/blob/master/spark/src/main/java/solution/PlayByPlay.java#L87) it to a `Row` object and create the schema.

The other option is to use `saveAsNewAPIHadoopFile`, but that requires more code and changes than you'd like.

Is there another better way of doing this that I'm missing? Otherwise, It would be great if the spark-avro library eased the burden of doing the initial ETL.

**Comment by JoshRosen** [comment]
This question looks slightly out of scope, to be honest, since you seem to be asking about how to take arbitrary data and make a DataFrame from it. However, in your specific example, I think your best bet is to use Spark's new `Datasets` API to automatically convert your `RDD[Weather]` into a `Dataset`. If the `Weather` class exposes Java bean properties for its fields then this should work more or less automatically.
