### ISSUE TITLE
Reading from s3 bucket recursively produces 404s and does not load avro data with Spark-Avro 2.0.1 on EMR 4.5.0

### ISSUE THREAD

**Issue by robbypond** [databricks/spark-avro#126]
I just upgraded to using Spark-Avro 2.0.1 on EMR 4.5.0 (Spark 1.6.1, Hadoop 2.7.2) from Spark-Avro 1.0.0 on EMR 3.8.0 (Spark 1.3.1, Hadoop 2.4.0).

The data is laid out in the bucket like **s3://bucket/date/dir1/dir2/somefile.avro**

Previously I was able to load a bucket recursively and process the data like:

```
sc.hadoopConfiguration(FileInputFormat.INPUT_DIR_RECURSIVE, "true")
val df = sqlContext.load("s3://some_bucket/some_date", "com.databricks.spark.avro")
```

And that worked fine. But now after upgrading I see a lot of logs in the spark-shell that display several 404s coming from the AWS S3 requests, and even a simple count will return 0. Making the load call with a full path to a folder contains the avro files works as expected. Also using wildcards will work like so:

```
val df = sqlContext.load("s3://some_bucket/*/*/*", "com.databricks.spark.avro")
```

I did notice that a new DataFileReader based on Spark 1.4 was added in 2.0.1 and if I downgrade to Spark-Avro 1.0.0 my previous code based on Spark 1.3.1 will still work.

Is this a bug? Or does recursive loading no longer work with the latest version?

**Comment by JoshRosen** [comment]
Current best guess: the old code was returning all S3 files matching the key prefix, e.g. doing complete recursive list, whereas new doesn't. It would be good to isolate this to see whether it's a `spark-avro` specific problem by trying this with Spark text file data sources, etc.

Since this ticket is kind of stale, I'm going to close it to declutter our backlog, but please file a new ticket if you still need help. Thanks!
