### ISSUE TITLE
Using of newer version of AVRO library.

### ISSUE THREAD

**Issue by nazariy-balkovskyy** [databricks/spark-avro#133]
Hello. I'm curious about using newer version of AVRO library. So at this moment the latest version is 1.8 but your library uses 1.7. Are you planning to add support for newer AVRO library?

**Comment by JoshRosen** [comment]
Unless we're willing to drop support for older Avro versions, I think we want to continue compiling and testing against Avro 1.7. What happens if you try pulling in Avro 1.8 by adding an explicit dependency on the newer version in order to override this library's dependency? Does everything work or do things break?

I think it's important to continue supporting 1.7.x because it may be the provided version in many Hadoop distributions so we need to be compatible with it.

**Comment by JoshRosen** [comment]
I just tested things out and it looks like this library's own unit tests work fine when run with Avro 1.8.x as the runtime Avro version (see #193). Given this, I'm going to go ahead and close this as "not an issue" for now. I suspect that you're asking about Avro 1.8 support because there are new Avro features introduced in that version which you'd like to see supported here. If that's the case, could you please file new issues mentioning those specific new/unsupported features?
